### ISSUE TITLE
템플릿관리 뷰

### ISSUE THREAD

**Issue by moonsungjun** [Taebu/prq#100]
https://prq.co.kr/prq/template/view/84/page/1

![image](https://user-images.githubusercontent.com/19964344/47887730-5b15ba00-de84-11e8-8726-585ecd769543.png)

다른페이지 뷰가 나옴

**Comment by Taebu** [comment]
올바른 url
https://prq.co.kr/prq/template/view/bt_template/bt_no/84/page/1

지금 수정 후 나오는 url 
https://prq.co.kr/prq/template/view/84/page/1

올바른 url 로 개선
https://prq.co.kr/prq/template/view/bt_template/bt_no/84/page/1

**Comment by Taebu** [comment]
수정 완료
개선 전
```php
alert('수정되었습니다.',
 '/prq/template/view/'.$this->input->post('bt_no', TRUE).'/page/'.$pages);
```
개선후
```php
alert('수정되었습니다.', 
sprintf('/prq/template/view/bt_template/bt_no/%s/page/%s',
$this->input->post('bt_no', TRUE),
$pages)
);
```
