### ISSUE TITLE
알림톡결제 플러스친구 선택 후 템플릿코드 선택값 확인요청

### ISSUE THREAD

**Issue by moonsungjun** [Taebu/prq#101]
https://prq.co.kr/prq/atapay/view/prq_ata_pay/ap_no/54/page/1

![image](https://user-images.githubusercontent.com/19964344/47889134-beefb100-de8b-11e8-95ff-8524af8b9766.png)

**Comment by Taebu** [comment]
수정  - 확인 요청요망
