### ISSUE TITLE
알림톡결제에서 정기결제 작동여부 확인

### ISSUE THREAD

**Issue by moonsungjun** [Taebu/prq#102]
https://prq.co.kr/prq/atapay/view/prq_ata_pay/ap_no/6/page/50

![image](https://user-images.githubusercontent.com/19964344/47889571-f7908a00-de8d-11e8-817c-245e6d0f580a.png)

**Comment by Taebu** [comment]
crontab 에서 확인 해야 함.

**Comment by Taebu** [comment]
개선전 초기화 
```
# 매일 한번씩 자정에 ata_pay 정보 값갱신 (limit 초기화)
# 0 0 * * * sh /etc/sh/set_ata_pay_day.sh
```

개선후 주석 해제
```
# 매일 한번씩 자정에 ata_pay 정보 값갱신 (limit 초기화)
0 0 * * * sh /etc/sh/set_ata_pay_day.sh
```
