### ISSUE TITLE
상점페이지에 ATA 상태값 변경 기능 추가

### ISSUE THREAD

**Issue by moonsungjun** [Taebu/prq#105]
https://prq.co.kr/prq/store/modify/prq_store/board_id/1664/page/1

![- -2](https://user-images.githubusercontent.com/19964344/47900309-c9c43900-debf-11e8-93ff-a86bc566a018.png)

**Comment by Taebu** [comment]
![image](https://user-images.githubusercontent.com/7663572/47978303-5fe6a200-e100-11e8-92d1-0345e55a8f86.png)
