### ISSUE TITLE
알림톡결제 리스트 "코드" 추가

### ISSUE THREAD

**Issue by moonsungjun** [Taebu/prq#106]
https://prq.co.kr/prq/store/lists/prq_ata_pay/page/1

![- -1](https://user-images.githubusercontent.com/19964344/47902211-07779080-dec5-11e8-8568-c8d6495dee57.png)

**Comment by moonsungjun** [comment]
총판도 들어가야되는데...대리점 코드만 들어가면 됩니다.

**Comment by Taebu** [comment]
![image](https://user-images.githubusercontent.com/7663572/47980486-3717da00-e10b-11e8-95a4-ca13fa7703b6.png)
