### ISSUE TITLE
템플릿관리 정규식코드 수정 에러

### ISSUE THREAD

**Issue by moonsungjun** [Taebu/prq#107]
https://prq.co.kr/prq/template/modify/bt_template/bt_no/86/page/1
![image](https://user-images.githubusercontent.com/19964344/47914535-60562180-dee3-11e8-9f05-f13d3718c729.png)

정규식 코드 key value 수정이 안됨.

**Comment by Taebu** [comment]
root@175.126.111.21:/var/www/html/prq/application/models/template_m.php
이전 오류 코드
```php
$_array['bt_regex']=join("&",$reg_array);
```

수정 코드
```php
$modify_array['bt_regex']=join("&",$reg_array);
```
