### ISSUE TITLE
톡톡메시지 PC / APP 상태값 정리

### ISSUE THREAD

**Issue by moonsungjun** [Taebu/prq#109]
PC (1시간 단위로 log체크)
정상 48시간 이하는 log -> 정상
경고 48시간 이상은 log -> 경고
점검 72시간 이상은 log -> 점검
알수없음 단 한번도 log가 없을 시 -> 알수없음

APP
logs -> gcm
전달성공 -> 정상
전달실패 -> 점검

가맹점 상태값이
대기,해지,승인거부,연계완료 4개는
PC / APP log 상태값을 체크하지 않습니다.

처리중, 승인 이 두개 상태만
PC / APP log 상태값을 체크합니다.

**Comment by Taebu** [comment]
PC 경우 시간 갱신 문제는 해결 완료.

Mobile 경우 시간 갱신 문제는 미해결 
- GCM 로그에서 갱신.

2시간 마다 상태를 갱신하는 문제와 필요할때 상태 갱신하는 문제

**Comment by Taebu** [comment]
2시간 마다 프로그램 돌리는 예시.
1. prq_member.mb_talktalk_pc_unixtime 이 0 이상인 것을 조회한 만큼 반복한다.
1-1. mb_talktalk_pc_unixtime과 현재 시간을 비교하여 입력시간을 로그시간 차이 값을 구한다.
1-2. 구한 로그시간 차이를 
72시간 이상는 "점검" 72x60x60<value
48시간 이하는 "정상" 48x60x60>value
48시간 이상은 "경고" 48x60x60<value

1-3. 위의 값 status 상태 값을 정한다.
2. 끝낸다.

- android 도 마찬가지로 진행
crontab에 구현 할것
