### ISSUE TITLE
token_id 정보 가맹점목록 페이지에 추가

### ISSUE THREAD

**Issue by moonsungjun** [Taebu/prq#114]
https://prq.co.kr/prq/franchise/view/prq_member/board_id/75/page/1

veiw 페이지 token_id , 날짜시간 정보 추가요청

![token_id](https://user-images.githubusercontent.com/19964344/48401241-eee06380-e76b-11e8-88ad-ae0ecd107c33.png)

**Comment by Taebu** [comment]
구현 완료 확인 요망
