### ISSUE TITLE
템플릿관리 정규식 코드 key value 추가

### ISSUE THREAD

**Issue by moonsungjun** [Taebu/prq#115]
![image](https://user-images.githubusercontent.com/19964344/48743776-e75b1600-eca7-11e8-9459-d5f626771342.png)

key name #{주문시간} / key value ->OCID 작성일자 참고

key name #{카카오주문하기} / key value -> 상점에서 카카오주문하기 url 참고

**Comment by Taebu** [comment]
at_no: 14208
at_subject: 알림톡페이테스트
at_content: 안녕하세요. 고객님
[사천성황궁쟁반짜장] 입니다.

고객님이 주문하신 음식을 맛있게 준비하여 배달해드리겠습니다.

:arrow_forward:매장번호 : 050-4110-6767
:arrow_forward:매장홈페이지 : http://prq.co.kr/prq/page/1603
:arrow_forward:포인트 : 첫 다운로드 2,000원 적립되었습니다.

요즘 트랜드에 맞게 배달음식을 주문 시 마다 현금적립 어플을 새롭게 출시 하였습니다.
고객님만을 위한 배달어플을 지금 확인 하세요!

적립금 관련 궁금한 점은 1599-9495 으로 문의해 주세요

"배달팡팡" 앱 포인트 확인 링크
http://bdpp.cashq.co.kr/m/p/
bp_appid: prq043
bt_code: GR00002
date_client_req: 2018-11-21 11:47:47
at_ismms: false
at_receiver: 0612479800
at_sender: 0612618200
at_date: 2018-11-21
at_imgurl:
at_ipaddr:
st_no: 1603
at_mmt_no: 14063
at_month_cnt: 318
at_month_limit: 1000
at_status: 2
ap_no: 271
at_result:
at_datetime: 2018-11-21 11:48:01

**Comment by Taebu** [comment]
ocid 작성일자 무시 
ata 기록 시간인 

주문시간| keyvalue 
--|--
#{주문시간}|prq_ata_log.date_client_req
#{카카오주문하기}|store.kakao_order_url

**Comment by Taebu** [comment]
![image](https://user-images.githubusercontent.com/7663572/48823762-6d10bb80-eda5-11e8-81f4-8341baf6e92c.png)
