### ISSUE TITLE
상점 카카오주문하기 url 입력 추가

### ISSUE THREAD

**Issue by moonsungjun** [Taebu/prq#116]
![url](https://user-images.githubusercontent.com/19964344/48744381-60f40380-ecaa-11e8-8496-a2ef09940643.png)

상점 정보에 카카오 주문하기 url 입력칸 추가

**Comment by Taebu** [comment]
code 5007추가 
```sql
insert into prq_codes set 
code=5007,
pcode=5000,
code_name='카카오주문하기 url',
code_value='카카오 주문하기 ATA 알림톡에 추가 하기 위한것 20181120 

상점 카카오주문하기 url 입력 추가 #116
https://github.com/Taebu/prq/issues/116',
use_bit=1;
```
codes.c5007
store.tel

store.kakao_order_url
- codes.c5007
추가 

매장명	store.name
매장번호(050)	store.tel
매장홈페이지	store.homepage
매장포인트	store.point

crontab -e
/etc/sh/set_ata.sh

root@175.126.111.21:/var/www/html/prq/application/views/crontab/ata_v.php
```php
line 235
		$store=array(
			"name"=>$st_names,
			"tel"=>$st_vtel[$li->st_no],
			"homepage"=>sprintf("http://prq.co.kr/prq/page/%s",$li->st_no),
			"point"=>"첫 다운로드 2,000".

		);
		
		$agencyMember=array(
			"point_items"=>"5회 주문시, 최대 10,000원\n10회 주문시, 최대 20,000원",
			"min_point"=>"15,000",
			"cell"=>"010-7743-0009");

		$function=array(
			"get_rand_int"=>get_rand_int(),
		);
```
SELECT * FROM `prq_ata_log` WHERE 1=1 and at_status in (1,2) order by at_no desc limit 15;

**Comment by Taebu** [comment]
http://prq.co.kr/prq/ajax/get_codes/st_no

사용 예)
http://prq.co.kr/prq/ajax/get_codes/438

**Comment by Taebu** [comment]
이부분 수정
https://github.com/Taebu/prq/blob/002311cd1582a5d7270a5bd34fe48a62a4dc9d0f/prq/application/views/crontab/ata_v.php#L239-L245
