### ISSUE TITLE
prq 모바일홈페이지 바로가기 개선요청

### ISSUE THREAD

**Issue by moonsungjun** [Taebu/prq#117]
테스트 홈페이지
http://prq.co.kr/prq/page/1681/

경쟁사 바로홈피 홈페이지
http://027809244.bdp.kr/

삼성인터넷 접속 시 바로가기 팝업창 정상
![screenshot_20181126-103137_samsung internet](https://user-images.githubusercontent.com/19964344/48988085-cb071f80-f166-11e8-94cb-1a07bccb1276.jpg)

네이버앱으로 접속 시 바로가기 팝업창 안나옴
![screenshot_20181126-103115_naver](https://user-images.githubusercontent.com/19964344/48988092-dbb79580-f166-11e8-9cce-0e3e6b0f8865.jpg)

삼성인터넷 , 네이버앱으로 접속해도 바로가기 팝업창 나오도록 개선요청

**Comment by Taebu** [comment]
root@175.126.111.21:
/var/www/html/prq/application/views/page/view_v.php

chrome 브라우저일때의 부분을 제거
```javascript
// if(cookie.get("chk7days")=="true"
//  ||jindo.$Agent().os().ios
//  ||jindo.$Agent().os().win
//  ||jindo.$Agent().navigator().getName()=="chrome")

if(cookie.get("chk7days")=="true"
||jindo.$Agent().os().ios
||jindo.$Agent().os().win)

```
