### ISSUE TITLE
prq ocid call log 적립 시스템 개발요청

### ISSUE THREAD

**Issue by moonsungjun** [Taebu/prq#129]
https://prq.co.kr/prq/store/modify/prq_store/st_no/1802/page/1

![prq_store](https://user-images.githubusercontent.com/19964344/59658186-e78ba780-91dd-11e9-897a-8610bfa5a319.png)

**Comment by moonsungjun** [comment]
biz_code : prqpoint01
0507_event :
prqpoint01 | fivept | 경기 고양시 일산동구 백석동 | 2019-06-01 | 2019-08-31 | prqpoint01_1 | 1 | 10 | 24 | 진행중 | 자동 | n

**Comment by Taebu** [comment]
시아이디포인트사용여부
code_5008
```sql
INSERT INTO `prq`.`prq_codes` (`code`, `pcode`, `code_name`, `code_value`, `use_bit`)
 VALUES ('5008', '5000', '시아이디포인트사용여부', '시아이디 포인트를 사용할지를 결정합니다. YN', '1');
```

시아이디포인트적립금액
code_5009
```sql
INSERT INTO `prq`.`prq_codes` (`code`, `pcode`, `code_name`, `code_value`, `use_bit`)
 VALUES ('5009', '5000', '시아이디포인트적립금액', '시아이디 포인트 적립금액', '1');
```

시아이디포인트 연결 biz_code 
code_5010
```sql
INSERT INTO `prq`.`prq_codes` (`code`, `pcode`, `code_name`, `code_value`)
 VALUES ('5010', '5000', '시아이디포인트 연결 biz_code', '시아이디 포인트를 연결할 biz_code를 작성합니다.');
```

**Comment by Taebu** [comment]
![image](https://user-images.githubusercontent.com/7663572/59890096-4fbed100-940a-11e9-971e-ae0a95491d21.png)
적용 완료.
