### ISSUE TITLE
가맹점관리 신규 "N가맹점 목록" 리스트 추가

### ISSUE THREAD

**Issue by moonsungjun** [Taebu/prq#139]
https://prq.co.kr/prq/franchise/lists/prq_member/page/1

![1](https://user-images.githubusercontent.com/19964344/70289865-843c1300-1819-11ea-869f-f1f68e613acd.jpg)
![2](https://user-images.githubusercontent.com/19964344/70289866-843c1300-1819-11ea-8e3a-7b2a0e1a6f21.jpg)
![3](https://user-images.githubusercontent.com/19964344/70289868-84d4a980-1819-11ea-9974-7e79eb5c763f.jpg)
![4](https://user-images.githubusercontent.com/19964344/70289869-84d4a980-1819-11ea-856b-bab978513376.jpg)
![5](https://user-images.githubusercontent.com/19964344/70289870-84d4a980-1819-11ea-8115-11bea724add9.jpg)

[Binder1.pdf](https://github.com/Taebu/prq/files/3930062/Binder1.pdf)

**Comment by Taebu** [comment]
1|2
--|--
서류접수|submit
설치|install
1차지급|1st_payment
2차지급|2nd_payment

1|2
--|--
대기|wait
접수|order
설치중|installing
보류|withhold
완료|complete
진행중|in_progress
심사중|decision_in_process

**Comment by Taebu** [comment]
```sql
INSERT INTO `prq`.`prq_codes` (`code`, `pcode`, `code_name`, `code_value`, `use_bit`) 
VALUES 
('4001', '4000', 'fr_submit', '네이버 테이블 주문 서류접수값', '1'),
('4002', '4000', 'fr_install', '네이버 테이블 주문 설치', '1'),
('4003', '4000', 'fr_1st_payment', '네이버 테이블 주문 1차지급', '1'),
('4004', '4000', 'fr_2st_payment', '네이버 테이블 주문 2차지급', '1'),
('4005', '4000', 'fr_posname', '네이버 테이블 주문 포스네임', '1');
```
