### ISSUE TITLE
PRQ 가맹점 mno정보

### ISSUE THREAD

**Issue by moonsungjun** [Taebu/prq#53]
http://prq.co.kr/prq/franchise/view/prq_member/board_id/118/page/1

MNO 정보
통신사   KT
발송번호    01065119969 문자 구분       MMS
안드로이드 버전  6.0.1   단말기       SM-N916K
일일문자발송제한    0   \* 중복발송제한        0

일일문자발송제한 0
중복발송제한 0

위 두개가 수정이 안됨.

**Comment by Taebu** [comment]
조치 되었음. mno 정보 수정.
