### ISSUE TITLE
톡톡메시지 발송시 (일반전화) GCM 발송 개선요청

### ISSUE THREAD

**Issue by moonsungjun** [Taebu/prq#68]
http://prq.co.kr/prq/logs/lists/cid

상태 -> 일반전화 

는

gcm 미 발송으로 개선요청

사유
매장사장 핸드폰에서 일반번호로 MMS 발송 시
[0226157347]전송이 정상적으로 이루어지지 않았습니다 다시 시도해 주십시오

이런식으로 통신사에서 안내 문자가 계속 발송된다고 함.

**Comment by Taebu** [comment]
일반 번호인 경우 전송하지 않습니다.
```java
boolean is_hp=false; //추가
is_hp=checkPattern("phone",dao.rs().getString("cd_callerid"));
//추가
if(is_hp){
set_gcm();
set_mms();
}

```
