### ISSUE TITLE
깻잎두마리칩킨 문자 대량 발송 개발요청

### ISSUE THREAD

**Issue by moonsungjun** [Taebu/prq#81]
http://prq.co.kr/prq/board/write/

![image](https://user-images.githubusercontent.com/19964344/29392791-0004c138-833b-11e7-9530-ef04b012cc6a.png)

**Comment by Taebu** [comment]
![prq_](https://user-images.githubusercontent.com/7663572/29398224-5ef6909a-835e-11e7-9bf3-578f83de6765.PNG)
대량 발송 성공, 실패 갯수[ GCM 전송의 경우 ] 카운트 하여 적용 완료.
