### ISSUE TITLE
세종옐로우톡 톡톡메세지 개발 요청

### ISSUE THREAD

**Issue by moonsungjun** [Taebu/prq#83]
톡톡메세지 기존 문자발송 부분을 옐로우톡 발송도 되도록 개발요청

1. 분류 : 톡톡메세지 발송 , 옐로우톡 발송 2가지 발송방법을 선택해서 보낼 수 있음.

2. 발송제한 : 
월 발송건수를 제한 할 수 있는 기능 . 
(예시: 월 1000건 발송 제한)  발송 단위 조정 가능하도록 개발.
상점별로 발송 제한을 해야됨.

3. 대리점 등급 별로 옐로우아이디 지정
각 대리점마다 옐로우아이디가 다름.

예시
A대리점 -> @배달캐시큐
B대리점 -> @배달톡톡
C대리점 -> @배달장독대

**Comment by moonsungjun** [comment]
[java_agent_manual_v1.6.4(2017.11.10).pdf](https://github.com/Taebu/prq/files/1473442/java_agent_manual_v1.6.4.2017.11.10.pdf)

**Comment by Taebu** [comment]
cashq.co.kr
- 172.126.82.182

prq.co.kr
- 175.126.111.21

개발사 컴퓨터
- 123.142.52.92 ( 현재 아이피 )
- 유동 아이피라 123.142.52.90 - 123.142.52.99 까지 변동 가능성 있어서 할당 바람

**Comment by Taebu** [comment]
20페이지에 보면 - 에이전트 3개 설치 이유?

**Comment by moonsungjun** [comment]
세종텔레콤 기술지원팀
대표전화 1688-2200
ARS 3번

세종텔레콤 주식회사
영업본부 유통망사업팀
조순행 매니저
010-9043-8074

**Comment by Taebu** [comment]
- 통화 결과
포트
7000 : SMS
7100 : MMS
7250 : 카카오톡
7200 : 메세지 수신결과 포트

에이전트 3개 설치는 다중으로 서비스 할 때만 필요한것이라 설명

**Comment by moonsungjun** [comment]
ㅇㅋ

**Comment by Taebu** [comment]
- 2017-11-16 (목) 14:26:05, 세종텔레콤 건당 6원 정책 때문에 이전에서 비즈톡도 동일한 조건을 제시 하여 조정 잠정 세종 텔레콤 카카오 발송 건은 현시간 부로 중단.
