### ISSUE TITLE
요기요 주문문자 서버 정의url

### ISSUE THREAD

**Issue by moonsungjun** [Taebu/prq#97]
![image](https://user-images.githubusercontent.com/19964344/46997841-ca3ca000-d15b-11e8-9ab5-7236cadb6122.png)

![image](https://user-images.githubusercontent.com/19964344/46997859-d6286200-d15b-11e8-9f00-dfaf5f1a93dc.png)

**Comment by Taebu** [comment]
No | data_name | data_name (eng) | dataType | comment
-- | -- | -- | -- | --
1 | 주문번호 | yo_tradeid | int | 기본키 값
2 | 주문시간 | yo_order_datetime | datetime | 2018-01-01 13:00:00
3 | 고객전화번호 | yo_hp | varchar(20) | 0504-####-####
4 | 배달주소 지번 | yo_address_jibun | varchar(2000) |  
5 | 배달주소 도로명 | yo_address_road | varchar(2000) | [도로명] 제거
6 | 고객요청사항 | yo_customer_specific_requirements | text |  
7 | 최종결제금액 | yo_price | int | 숫자만
8 | 결제방법 | yo_paytype | varchar(255) |  
9 | 결제코드 | yo_paycode | varchar(6) | 선결제=prepay, 카드=card, 현금=cash

**Comment by Taebu** [comment]
```sql
CREATE TABLE `yogiyo_order` (
  `yo_no` int(11) NOT NULL AUTO_INCREMENT,
  `yo_tradeid`	int	 DEFAULT 0 COMMENT '주문번호',
  `yo_order_datetime` datetime	COMMENT '주문시간 2018-01-01 13:00:00',
  `yo_customer_phone` varchar(20) DEFAULT NULL COMMENT '고객전화번호	0504-####-####',
  `yo_address_jibun` varchar(2000) DEFAULT '' COMMENT '배달주소 지번',
  `yo_address_road` varchar(2000) DEFAULT '' COMMENT '배달주소 도로명 [도로명] 제거',			
  `yo_customer_specific_requirements` text COMMENT '고객요청사항',		
  `yo_price` int(11) NOT NULL DEFAULT 0 COMMENT '최종결제금액',
  `yo_paytype` varchar(255) DEFAULT '' COMMENT '결제방법',					
  `yo_paycode` varchar(6) DEFAULT '' COMMENT '결제코드 선결제=prepay, 카드=card, 현금=cash',							
  `yo_datetime` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '요기요 주문 입력일',
  PRIMARY KEY (`yo_no`)
) DEFAULT CHARSET=utf8 COMMENT='요기요 주문 입력일 - 20181017 v1';	
```

**Comment by Taebu** [comment]
http://prq.co.kr/ajax/set_yogiyo_order
- 중지 이유 요기요 결제 프로그램인 안드로이드 앱 설치시 요기요 서버 측에서 SMS 전송치 않음. 개발의 불필요성 판단하여 어제 
2018-10-17 (수) 15:46:18 중지 회의 검토

오늘 2018-10-18일 (목) 오전 회의 중지 대리운전 앱 만들기로 전향
