### ISSUE TITLE
알림톡 입금 목록 에러확인

### ISSUE THREAD

**Issue by moonsungjun** [Taebu/prq#98]
https://prq.co.kr/prq/store/lists/prq_ata_pay/page/1

![image](https://user-images.githubusercontent.com/19964344/47886648-b93f9e80-de7e-11e8-8ffe-4d4a7f54aaaf.png)

**Comment by Taebu** [comment]
연산이라는 업체를 이고은 과장이 잘못 등록.
```sql
DELETE FROM `prq`.`prq_ata_pay` WHERE `ap_no`='53';
```
삭제 조치로 해결
