### ISSUE TITLE
템플릿 관리 오류

### ISSUE THREAD

**Issue by moonsungjun** [Taebu/prq#99]
https://prq.co.kr/prq/template/modify/bt_template/bt_no/84/page/1

![image](https://user-images.githubusercontent.com/19964344/47887154-43890200-de81-11e8-9970-8cbfdd7146fd.png)

**Comment by Taebu** [comment]
모델에 들어갈 항목이 컨트롤러에 있어 생긴 문제

**Comment by Taebu** [comment]
해결
